namespace Aero.Domain.Enums;

public enum Module
{
      DASHBOARD,EVENTS,LOCATION,ALERT,OPERATOR,DEVICE,DOOR,USER,ACCESSLEVEL,ACCESSAREA,TIME,TRIGGER,REPORT,SETTING,MAP,CONTROLPOINT,MONITORPOINT,MONITORGROUP
}
